In [1]:
#同时输出一个cell多个结果
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity='all' 
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score


In [2]:
iris=pd.read_csv('d:/iris.csv')  #读入iris数据集，150个样本的5个特征 sepallength（花萼长度）petallength（花瓣长度），三个类别
#根据特征分为两部分，分别为预测特征target 和数据特征集 data

iris_data=iris.iloc[:,:4]
iris_data
iris_target=iris['Species']
iris_target

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: Species, Length: 150, dtype: object

## 留出法

In [3]:
#按比例划分训练集和测试集   4个参数 数据集，标签
X_train,X_test,y_train,y_test = train_test_split(iris_data,iris_target,test_size=0.3,stratify=iris_target)
y_test.value_counts()

setosa        15
versicolor    15
virginica     15
Name: Species, dtype: int64

In [4]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)
gnb.score(X_test,y_test) #准确率
confmat= confusion_matrix(y_true=y_test,y_pred=y_pred)#输出混淆矩阵
print (confmat)
print ('precision:%.3f' %precision_score(y_true=y_test, y_pred=y_pred,average='macro'))
print ('recall:%.3f' %recall_score(y_true=y_test, y_pred=y_pred,average='macro'))
print ('F1:%.3f' %f1_score(y_true=y_test, y_pred=y_pred,average='macro'))

0.9777777777777777

[[15  0  0]
 [ 0 15  0]
 [ 0  1 14]]
precision:0.979
recall:0.978
F1:0.978


## 交叉验证

In [5]:
#交叉验证法
from sklearn.model_selection import cross_val_score
clf = GaussianNB()  # Naiive Bayes 
scores = cross_val_score(clf,iris_data, iris_target, cv=5)  #5折交叉验证
scores.mean() # score 平均值

0.9533333333333334